# Documentation: https://github.com/codecov/support/wiki/Codecov-Yaml

codecov:
  # CodeCov should only wait for CI's that run coverage tests
  # DAutoTester and auto-tester are not in the default list
  ci:
    - "circleci.com"
  notify:
    after_n_builds: 1  # send notifications after the first upload
  bot: dlang-bot

coverage:
  precision: 3
  round: down
  range: 80...100

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project: true
    patch: true
    changes: false
  fixes:
    - "test/.*/::src/"
    - "fail_compilation/::src/"

comment: false
