steps:
  - script: |
      :: Use Windows CRLF line endings for checked-out text files
      git config --global core.autocrlf true
      set
    displayName: Print environment variables
  - checkout: self
    fetchDepth: 1
  - script: |
      @echo on
      call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
      FOR /F "tokens=* USEBACKQ" %%F IN (`where cl.exe`) DO (SET MSVC_CC=%%~fsF)
      FOR /F "tokens=* USEBACKQ" %%F IN (`where lib.exe`) DO (SET MSVC_AR=%%~fsF)
      bash --version
      sh --login .azure-pipelines/windows.sh
    displayName: Build DMD
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: windows-$(ARCH)
      targetPath: artifacts
    displayName: Publish artifacts
